version: "3"
services:
    frontend:
        container_name: hh_web
        build:
            context: ./Frontend/client
            dockerfile: Dockerfile
        image: kena/hh_client
        ports:
            - "3000:3000"
        # volumes:
        #     - ./client:/usr/src/app
    backend:
        container_name: hh_server
        build:
            context: ./Backend
            dockerfile: Dockerfile
        image: kena/hh_server
        ports:
            - "3001:3001"
        # volumes:
        #     - ./server:/usr/src/app
        
      